//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTestamentLeedsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CImage
    {
        public CImage()
        {
            this.CEvents = new HashSet<CEvent>();
        }
    
        public int imageID { get; set; }
        public byte[] imageFile { get; set; }
        public string title { get; set; }
        public int type { get; set; }
        public string imageMimeType { get; set; }
        public string description { get; set; }
        public string userName { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        public virtual ICollection<CEvent> CEvents { get; set; }
    }
}
